[tools]
# Languages
node = ["22", "23"]
java = ["21", "17"]
python = "3.12"

# Build tools
maven = "3.9"
gradle = "8"
pnpm = "latest"

# CLI tools
eza = "latest"
fd = "latest"
delta = "latest"
lazydocker = "latest"
lazygit = "latest"
bat = "latest"
ripgrep = "latest"
btop = "latest"
jq = "latest"
fzf = "latest"
gh = "latest"
neovim = "latest"
tlrc = "latest"
yq = "latest"
zoxide = "latest"
curlie = "latest"
dust = "latest"
k9s = "latest"
glow = "latest"
direnv = "latest"

[settings]
experimental = true
