
live_config_reload = true

import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[window]
opacity = 0.85
dynamic_padding = false
decorations = "None"
blur = true
resize_increments=true
dynamic_title= true

[selection]
save_to_clipboard = true

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "T", mods = "Control|Shift", action = "ToggleFullscreen" },
]


